######################################################################
# Automatically generated by qmake (3.0) ven. oct. 2 10:30:30 2015
######################################################################

TEMPLATE = app
TARGET = Webcrack
INCLUDEPATH += .
QT += widgets gui network

# Input
SOURCES += src/webcrack.cpp
