######################################################################
# Automatically generated by qmake (3.0) ven. oct. 2 10:30:30 2015
######################################################################

TEMPLATE = app
TARGET = Webcrack
INCLUDEPATH += ./ include/
QT += widgets gui network

# Input
HEADERS += include/mainwindow.h
SOURCES += src/webcrack.cpp src/mainwindow.cpp
